version: 2
jobs:
  build:
    docker:
      - image: mbartling/utensor_ci
    steps:
      - checkout
      - run: git clone https://github.com/ThrowTheSwitch/Unity.git unity_temp
      - run: mv unity_temp/* unity/
      - run: find TESTS -type f -exec sed -e 's/\/fs\//TESTS\//g' -i {} \;
      - run: find uTensor/core/ -type f -exec sed -e 's/\/fs\//\//g' -i {} \;
      - run: cmake .
      - run: make
      - run: 
          name: Test
          command: ctest -VV
      - run:
          name: Generate code coverage
          command: lcov -c --directory . --output-file main_coverage.info
      - run: genhtml main_coverage.info --output-directory coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
        
