version: 2
jobs:
  build:
    docker:
      - image: mbartling/utensor_ci
    steps:
      - checkout
      - run: git clone https://github.com/ThrowTheSwitch/Unity.git unity_temp
      - run: mv unity_temp/* unity/
      - run: find TESTS -type f -exec sed -e 's/\/fs\//TESTS\//g' -i bak {} \;
      - run: cmake .
      - run: make
      - run: ctest -VV
